name: check-policies

on: [pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install fprettify
      - name: Run fprettify
        id: fprettify-check
        run: |
          echo "Running fprettify..."
          FPRETTIFY_OUTPUT=$(fprettify --config .fprettify.ini --diff --recursive src)
          echo "$FPRETTIFY_OUTPUT"
          {
            echo "fprettify_output<<EOF"
            echo "$FPRETTIFY_OUTPUT"
            echo "EOF"
          } >> $GITHUB_ENV
      - name: Check fprettify result
        if: env.fprettify_output != ''
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Code formatting issues found. Please run fprettify locally and commit the changes.')